#!/usr/bin/python3
import textract
import text_to_cloud
import argparse
import os
import os.path

lang_codes = {
'ab': 'abk',
'aa': 'aar',
'af': 'afr',
'ak': 'aka',
'sq': 'sqi',
'am': 'amh',
'ar': 'ara',
'an': 'arg',
'hy': 'hye',
'as': 'asm',
'av': 'ava',
'ae': 'ave',
'ay': 'aym',
'az': 'aze',
'bm': 'bam',
'ba': 'bak',
'eu': 'eus',
'be': 'bel',
'bn': 'ben',
'bi': 'bis',
'bs': 'bos',
'br': 'bre',
'bg': 'bul',
'my': 'mya',
'ca': 'cat',
'ch': 'cha',
'ce': 'che',
'ny': 'nya',
'zh': 'zho',
'cu': 'chu',
'cv': 'chv',
'kw': 'cor',
'co': 'cos',
'cr': 'cre',
'hr': 'hrv',
'cs': 'ces',
'da': 'dan',
'dv': 'div',
'nl': 'nld',
'dz': 'dzo',
'en': 'eng',
'eo': 'epo',
'et': 'est',
'ee': 'ewe',
'fo': 'fao',
'fj': 'fij',
'fi': 'fin',
'fr': 'fra',
'fy': 'fry',
'ff': 'ful',
'gd': 'gla',
'gl': 'glg',
'lg': 'lug',
'ka': 'kat',
'de': 'deu',
'el': 'ell',
'kl': 'kal',
'gn': 'grn',
'gu': 'guj',
'ht': 'hat',
'ha': 'hau',
'he': 'heb',
'hz': 'her',
'hi': 'hin',
'ho': 'hmo',
'hu': 'hun',
'is': 'isl',
'io': 'ido',
'ig': 'ibo',
'id': 'ind',
'ia': 'ina',
'ie': 'ile',
'iu': 'iku',
'ik': 'ipk',
'ga': 'gle',
'it': 'ita',
'ja': 'jpn',
'jv': 'jav',
'kn': 'kan',
'kr': 'kau',
'ks': 'kas',
'kk': 'kaz',
'km': 'khm',
'ki': 'kik',
'rw': 'kin',
'ky': 'kir',
'kv': 'kom',
'kg': 'kon',
'ko': 'kor',
'kj': 'kua',
'ku': 'kur',
'lo': 'lao',
'la': 'lat',
'lv': 'lav',
'li': 'lim',
'ln': 'lin',
'lt': 'lit',
'lu': 'lub',
'lb': 'ltz',
'mk': 'mkd',
'mg': 'mlg',
'ms': 'msa',
'ml': 'mal',
'mt': 'mlt',
'gv': 'glv',
'mi': 'mri',
'mr': 'mar',
'mh': 'mah',
'mn': 'mon',
'na': 'nau',
'nv': 'nav',
'nd': 'nde',
'nr': 'nbl',
'ng': 'ndo',
'ne': 'nep',
'no': 'nor',
'nb': 'nob',
'nn': 'nno',
'ii': 'iii',
'oc': 'oci',
'oj': 'oji',
'or': 'ori',
'om': 'orm',
'os': 'oss',
'pi': 'pli',
'ps': 'pus',
'fa': 'fas',
'pl': 'pol',
'pt': 'por',
'pa': 'pan',
'qu': 'que',
'ro': 'ron',
'rm': 'roh',
'rn': 'run',
'ru': 'rus',
'se': 'sme',
'sm': 'smo',
'sg': 'sag',
'sa': 'san',
'sc': 'srd',
'sr': 'srp',
'sn': 'sna',
'sd': 'snd',
'si': 'sin',
'sk': 'slk',
'sl': 'slv',
'so': 'som',
'st': 'sot',
'es': 'spa',
'su': 'sun',
'sw': 'swa',
'ss': 'ssw',
'sv': 'swe',
'tl': 'tgl',
'ty': 'tah',
'tg': 'tgk',
'ta': 'tam',
'tt': 'tat',
'te': 'tel',
'th': 'tha',
'bo': 'bod',
'ti': 'tir',
'to': 'ton',
'ts': 'tso',
'tn': 'tsn',
'tr': 'tur',
'tk': 'tuk',
'tw': 'twi',
'ug': 'uig',
'uk': 'ukr',
'ur': 'urd',
'uz': 'uzb',
've': 'ven',
'vi': 'vie',
'vo': 'vol',
'wa': 'wln',
'cy': 'cym',
'wo': 'wol',
'xh': 'xho',
'yi': 'yid',
'yo': 'yor',
'za': 'zha',
'zu': 'zul'
}


def render_wordcloud_from_document(doc_path, output_image_path, exclude_obvious, language):
    # added as submodule
    tessdata_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tessdata')
    os.environ['TESSDATA_PREFIX'] = tessdata_path

    if language in lang_codes.keys():
        language = lang_codes[language]

    text = textract.process(doc_path, output_encoding='utf-8', language=language).decode('utf-8')
    print(text)
    text_to_cloud.render_cloud_from_text(text, output_image_path, exclude_obvious)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--document', help='input document path', required=True)
    parser.add_argument('-o', '--output', help='output image path', required=True)
    parser.add_argument('-l', '--lang', help='image language', default='en', required=False)
    parser.add_argument('-ro', 
                        '--remove-obvious', 
                        help='exclude 15 percents of most frequent words',
                        required=False, 
                        dest='remove_obvious',
                        action='store_true')
    parser.set_defaults(remove_obvious=False)
    args = parser.parse_args()
    render_wordcloud_from_document(args.document, args.output, args.remove_obvious, args.lang)